# Generated by Django 5.0.2 on 2024-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EX', 'Exercise'), ('DT', 'Dieat'), ('HT', 'Health'), ('YG', 'Yoga'), ('MD', 'Meditation')], max_length=2)),
            ],
        ),
    ]
