# Generated by Django 5.0.2 on 2024-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=10, upload_to='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sets',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
