# Generated by Django 5.0.2 on 2024-02-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_image_product_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sets',
        ),
    ]
