# Generated by Django 5.0.2 on 2024-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sets',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
